### ISSUE TITLE
Why refactoring into SASS?

### ISSUE THREAD

**Issue by LockeAG** [bstaruk/starbase#68]
I'm just reading all the new changes on starbase, and why the abrupt change from PostCss to Sass?

**Comment by bstaruk** [comment]
Thanks for writing, @LockeAG 

PostCSS has been the biggest pain point in maintaining this repo because of the number of plugins it relies on just to be viable. Sass offers everything (and more) we had in our PostCSS setup, but with about 10 less dependencies and much cleaner Webpack configs.

Basically, I figured it was time to stop swimming up stream.

**Comment by LockeAG** [comment]
I experience myself some very slow compiling and bigger file sizes with sass , but lets give it try. 

I re-fork it, and also update the with `@babel/eslint-parser` and  `eslint-webpack-plugin` , I hope this may help to this repo

https://github.com/LockeAG/starbase

:)

**Comment by bstaruk** [comment]
@LockeAG Thank you for that! I didn't even realize those packages were archived/deprecated. I've swapped them in `develop` and they'll be included in the next release (in the next few days).

**Comment by bstaruk** [comment]
The feedback received in this PR should be all addressed in #69

Thank you again for your help @LockeAG 🥇
